#!/bin/bash

# kill any previous instance(s) of conky, then launch conky again
killall -q conky
conky --daemonize
# start glava audio visualizer
~/.glava_start
# launch polybar
bash ~/.config/polybar/hack/launch.sh
